services:
  - type: web
    name: projeto-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm run render-build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 24h
      - key: VITE_API_URL
        value: /api

